M48
; DRILL file {KiCad (6.0.10-dirty)} date Thu 22 Dec 2022 10:26:17 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-22T22:26:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-dirty)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X5.6712Y-4.0016
X5.6712Y-4.4016
T2
X6.125Y-2.16
X6.125Y-2.76
X6.975Y-2.16
X6.975Y-2.76
T3
X6.4398Y-2.9933
X6.4398Y-5.2767
X7.3453Y-2.9933
X7.3453Y-5.2767
T0
M30
